services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rabbani
      POSTGRES_PASSWORD: rabbani
      POSTGRES_DB: next15_ecommerce
    volumes:
      - ./postgres_data:/var/lib/postgres/data

volumes:
  postgres_data: